# Generated by Django 4.0.1 on 2023-10-10 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=50)),
                ('House_Name', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Pin', models.CharField(max_length=10)),
                ('Status', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Total_Amount', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=50)),
                ('Place', models.CharField(max_length=100)),
                ('Landmark', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Pin', models.CharField(max_length=10)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_PHARMA.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_image', models.CharField(max_length=200)),
                ('Manufacturer_Name', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=20)),
                ('Quantity', models.CharField(max_length=100)),
                ('Netvoldos', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('File', models.FileField(max_length=300, upload_to='')),
                ('Status', models.CharField(max_length=50)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_PHARMA.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Amount', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=50)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_PHARMA.customer')),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_PHARMA.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=100)),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_PHARMA.order')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_PHARMA.stocks')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='PRESCRIPTION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_PHARMA.prescription'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expiry_Date', models.CharField(max_length=100)),
                ('Shelf_Code', models.CharField(max_length=20)),
                ('Shelf_Rowno', models.CharField(max_length=20)),
                ('Shelf_Colno', models.CharField(max_length=20)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_PHARMA.stocks')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Feedback', models.CharField(max_length=200)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_PHARMA.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_PHARMA.login'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Complaint', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=100)),
                ('Reply', models.CharField(max_length=200)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_PHARMA.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Available_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=50)),
                ('Quantity', models.CharField(max_length=100)),
                ('PRESCRIPTION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_PHARMA.prescription')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_PHARMA.stocks')),
            ],
        ),
    ]
