# Generated by Django 4.0.1 on 2023-10-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_PHARMA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_Holder', models.CharField(max_length=100)),
                ('Account_Number', models.CharField(max_length=100)),
                ('Card_Number', models.CharField(max_length=100)),
                ('CVV', models.CharField(max_length=100)),
                ('Expiry_Date', models.DateField()),
                ('Balance_Amount', models.CharField(max_length=100)),
            ],
        ),
    ]
