# Generated by Django 4.0.1 on 2023-09-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_PHARMA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Status',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
