# Generated by Django 4.0.1 on 2023-10-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_PHARMA', '0003_alter_available_products_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='pin',
            new_name='Pin',
        ),
    ]
