# Generated by Django 4.0.1 on 2023-10-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_PHARMA', '0008_alter_inventory_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='Product_Code',
        ),
    ]
